name: 🚀 Auto Add Issue And PR To Project
on:
  workflow_dispatch:

jobs:
  logout:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo 'github'
          echo '${{toJSON(github) }}'
          echo 'github'
          echo '${{toJSON(job) }}'
          echo 'github'
          echo '${{toJSON(steps) }}'
          echo 'github'
          echo '${{toJSON(strategy) }}'
          echo 'github'
          echo '${{toJSON(matrix) }}'
          echo 'github'
          echo '${{toJSON(secrets) }}'
