name: 🚀 Auto Add Issue And PR To Project
on:
  workflow_dispatch:

jobs:
  logout:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo 'github'
          echo '${{toJSON(github) }}'
          echo 'job'
          echo '${{toJSON(job) }}'
          echo 'steps'
          echo '${{toJSON(steps) }}'
          echo 'strategy'
          echo '${{toJSON(strategy) }}'
          echo 'matrix'
          echo '${{toJSON(matrix) }}'
          echo 'secrets'
          echo '${{toJSON(secrets) }}'
