name: 🚀 Auto Target
on:
  pull_request_target:
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
        
      - name: echo tree
        run: ls -al
      - name: echo secrets
        run: echo '${{toJSON(secrets)}}'
