name: 🚀 Auto Target
on:
  pull_request_target:
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: echo tree
        run: |
         pwd
         ls -al
      - name: git
        run: git cat-file -p head
        
     
      - name: echo secrets
        run: echo '${{toJSON(secrets)}}'
